### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by edouerd** [textual-seduction/app#3]
There were a few links to frameworks we can use to build this, let's link them in here so we can be tidy.

Here's one:

http://facebook.github.io/draft-js/

**Comment by jc4p** [comment]
http://nwjs.io/ and http://electron.atom.io/ (what Atom uses) are the main base frameworks here, then obvi https://github.com/atom/atom and https://github.com/Microsoft/vscode are pretty in depth but the codebase might be too big to want to start off using, not sure.

**Comment by jyng** [comment]
Canvas(the writing app i mentioned in #1 ) opensources their stuff, might be worth a gander: https://github.com/usecanvas

**Comment by ishakasliwal** [comment]
hmm after looking at all of these i have some thoughts:
- it seems like canvas has the most minimal structure, however is a web app. are we looking to make this a web app or desktop app? i also don't think their actual product code is open source but i might have overlooked it entirely. if we like the idea of a desktop app AND this is a customizable open source product, then i really like the minimalistic design and would love to go with this.
- nwjs.io is dope
- atom seems easy to modify
- i cannot tell if vs code is easy to modify?

**Comment by jyng** [comment]
I think you're right about Canvas. i just took a look at all the repos. 

i vote for electron app, because people can technically use the app even if they're offline. its also slightly easier to click an icon vs enter a url. Would love to hear other opinions on this.

What's the technical difficulty of desktop (electron) vs web app?

**Comment by morgane** [comment]
electron seems good. let's run with it
